// 토큰 세트 → projectFiles 형태의 파일 생성 유틸

function generateColorFile(colors) {
  return `export const colors = ${JSON.stringify(colors, null, 2)};

export default colors;`;
}

function generateTypographyFile(typography) {
  return `export const typography = ${JSON.stringify(typography, null, 2)};

export default typography;`;
}

function generateSpacingFile(spacing, radius) {
  return `export const spacing = ${JSON.stringify(spacing, null, 2)};

export const radius = ${JSON.stringify(radius, null, 2)};

export default { spacing, radius };`;
}

function generateThemeFile(tokenSet) {
  return `// ${tokenSet.name} 통합 테마
export const theme = {
  colors: ${JSON.stringify(tokenSet.colors, null, 2)},
  typography: ${JSON.stringify(tokenSet.typography, null, 2)},
  spacing: ${JSON.stringify(tokenSet.spacing, null, 2)},
  radius: ${JSON.stringify(tokenSet.radius, null, 2)},
  shadows: ${JSON.stringify(tokenSet.shadows, null, 2)},
};

export default theme;`;
}

export function generateTokenFiles(tokenSet) {
  return {
    "colors.js": {
      code: generateColorFile(tokenSet.colors),
      type: "theme",
      label: "색상 토큰",
      desc: `${tokenSet.name}의 색상`,
      icon: "🎨",
      autoGenerated: true,
    },
    "typography.js": {
      code: generateTypographyFile(tokenSet.typography),
      type: "theme",
      label: "글자 토큰",
      desc: `${tokenSet.name}의 타이포그래피`,
      icon: "Aa",
      autoGenerated: true,
    },
    "spacing.js": {
      code: generateSpacingFile(tokenSet.spacing, tokenSet.radius),
      type: "theme",
      label: "간격·둥글기 토큰",
      desc: `${tokenSet.name}의 간격/둥글기`,
      icon: "↔",
      autoGenerated: true,
    },
    "theme.js": {
      code: generateThemeFile(tokenSet),
      type: "theme",
      label: "통합 테마",
      desc: `${tokenSet.name} 전체 토큰`,
      icon: "🎨",
      autoGenerated: true,
    },
  };
}

// CSS 변수 형태로 내보내기
export function generateCSSVariables(tokenSet) {
  const lines = [":root {"];
  Object.entries(tokenSet.colors).forEach(([k, v]) => {
    lines.push(`  --color-${k.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase())}: ${v};`);
  });
  Object.entries(tokenSet.spacing).forEach(([k, v]) => {
    lines.push(`  --spacing-${k}: ${v}px;`);
  });
  Object.entries(tokenSet.radius).forEach(([k, v]) => {
    lines.push(`  --radius-${k}: ${v}px;`);
  });
  Object.entries(tokenSet.shadows).forEach(([k, v]) => {
    lines.push(`  --shadow-${k}: ${v};`);
  });
  lines.push("}");
  return lines.join("\n");
}
